### ISSUE TITLE
发现问题了还在更新吗?

### ISSUE THREAD

**Issue by Levofloxacin** [justyour/labelGroupAndStream#1]

**Comment by justyour** [comment]
啥问题？自己可以下载代码修改

**Comment by Levofloxacin** [comment]
button文字超长的时候导致UI变形,会叠加..不会自动折行..
如果没时间,我看看自己怎么改一下吧,谢谢

**Comment by Levofloxacin** [comment]
如果有数组@[@[@"我很短我正常", @"222", @"333", @"444"],
                       @[@"我很短我正常", @"222", @"333", @"444"], 
                       @[@"我很短我正常", @"222", @"333", @"444"],
                       @[@"当我超级长的时候,超出了屏幕的宽度,并且只要我是第一个元素的话,那么UI就会错乱", @"222", @"只要我不是第一个元素.无论我多长,我都不会出现UI错乱这个问题, 但是屏幕不会显示我的宽度,所以需要改变Button的高度,然后固定一个宽度,最后给Title折行就可以了", @"444"]]

数据结构如果是这样的话就会有问题..
特别长的那个字符串会导致布局错乱..
我的解决办法就是判断一下字符串的宽度,如果超出屏幕部分,按钮的高度增加, 然后button的title折行

问题的根本原因在于,, 无论是数组里的那个数组,只要第一个index超出屏幕的长度,就会发生错乱问题.
我代码写的不怎样,只能想到下边的写法..
如果有时间,或者顺手维护一下该控件的话,麻烦您更新一下,谢谢..
      
  //创建按钮
        UIButton *but = [UIButton buttonWithType:UIButtonTypeCustom];
        [but setTitleColor:_contentNorColor forState:UIControlStateNormal];
        [but setTitleColor:_contentSelColor forState:UIControlStateSelected];
        [but setTitle:dataAr[i] forState:UIControlStateNormal];
        [self.scroller addSubview:but];
        but.titleLabel.font = _font;
        // 九宫格算法，每行放三个 margainX+(i%3)*(butWidth + 10)  margainY+(i/3)*(butHeight+10)
        //处理标签流
        CGFloat butWidth = contentSize.width + FTWidth(20);
        butorignX = alineButWidth + _maragin_x;
        alineButWidth = _maragin_x + butWidth + alineButWidth;
        if (alineButWidth >= self.width) {
            butorignX = _maragin_x;
            alineButWidth = butorignX + butWidth;
            but_totalHeight = current_rect.size.height + current_rect.origin.y + _maragin_y;
        }
        
//UIButton的宽度超出屏幕的宽度, button的高度增加, button.title 折行
        **_if (butWidth >= self.width) {
            but.titleLabel.lineBreakMode = NSLineBreakByWordWrapping;
            but.titleLabel.numberOfLines = 0;
            but.titleEdgeInsets = UIEdgeInsetsMake(0, 10, 0, 10);
            but.frame = CGRectMake(butorignX, but_totalHeight, self.width - 20, butHeight * 1.5);
        } else {
            but.frame = CGRectMake(butorignX, but_totalHeight, butWidth, butHeight);
        }_**

**Comment by justyour** [comment]
更新上去了

**Comment by Levofloxacin** [comment]
牛b..
感谢提供..
